 apiVersion: v1
 kind: Service
 metadata:
   name: watsonx-flask-deployment
 spec:
   type: NodePort    
   ports:
   - port: 5000
     targetPort: 5000
     nodePort: 30007
   selector:
     app: flasknode